# $schema: https://json.schemastore.org/github-workflow.json
name: Close issues without repro

on:
  schedule:
    - cron: '0 0 * * *'

defaults:
  run:
    shell: bash

env:
  FORCE_COLOR: true

permissions:
  contents: read

jobs:
  close-issues:
    if: github.repository == 'jcayzac/copepod-modules'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: needs repro
        uses: actions-cool/issues-helper@a610082f8ac0cf03e357eb8dd0d5e2ba075e017e # v3.6.0
        with:
          actions: close-issues
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: needs repro
          inactive-day: 3
