# $schema: https://json.schemastore.org/github-workflow.json
name: Main

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

env:
  FORCE_COLOR: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  no-pre:
    if: github.repository == 'jcayzac/copepod-modules'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Check no preview release
        run: |
          [ ! -e .changeset/pre.json ] || \
          [[ "$(jq -r '.mode' < .changeset/pre.json)" != "pre" ]] || {
            printf '%b' '\e[1;31mNo prereleases are allowed on the main branch.\e[0m'
            exit 1
          }
